spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=fintech
spring.datasource.password=fintech

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.fintech.kafka.event
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.fintech.kafka.event.PaymentCreatedEvent