spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=fintech
spring.datasource.password=fintech

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info